# This is a basic workflow to help you get started with Actions

name: Test1

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.ACTION_BOT}}

      #Create a file
      - name: Capture ENV
        run: env > gitub_env.txt
      - name: echo datetime
        run: echo "$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: git status
        run: git status
      - name: git add
        run: git add .
      - name: git commit
        run: |
          git config user.name "Action Bot"
          git config user.email "<>"
          git commit -m "action updates $(date +'%Y-%m-%dT%H:%M:%S')"
      - name: git push
        run: git push
